language: node_js
node_js:
  - "8"
script:
  - npm run test -- --coverage
  - npm run lint
after_script: "curl -s https://codecov.io/bash | bash"
branches:
  only:
    - master
    - /^greenkeeper.*$/
services:
  - redis-server
